export const airportList = [
  "Ha Noi (HAN)",
  "Ho Chi Minh (SGN)",
  "Da Nang (DAD)",
  "Quang Ninh (VDO)",
  "Hai Phong (HPH)",
  "Nghe An (VII)",
  "Hue (HUI)",
  "Khanh Hoa (CXR)",
  "Lam Dong (DLI)",
  "Binh Dinh (UIH)",
  "Can Tho (VCA)",
  "Kien Giang (PQC)",
  "Dien Bien (DIN)",
  "Thanh Hoa (THD)",
  "Quang Binh (VDH)",
  "Quang Nam (VCL)",
  "Phu Yen (TBB)",
  "Gia Lai (PXU)",
  "Dak Lak (BMV)",
  "Kien Giang (VKG)",
  "Ca Mau (CAH)",
  "Ba Ria – Vung Tau (VCS)"
];